package org.tis.tools.abf.module.sys.dao;
import com.baomidou.mybatisplus.mapper.BaseMapper;
import org.tis.tools.abf.module.sys.entity.SysRunConfig;
/**
 *
 * 系统参数表(SysRunConfig)的DAO
 *
 * @author generated by tools:gen-dao
 *
 */
public interface SysRunConfigMapper extends BaseMapper<SysRunConfig> {

}
