package org.tis.tools.abf.module.om.entity;

import com.baomidou.mybatisplus.activerecord.Model;
import com.baomidou.mybatisplus.annotations.TableName;
import org.tis.tools.core.utils.StringUtil;

import java.io.Serializable;

/**
 * Model class of 应用工作组列表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@TableName("OM_EMP_GROUP")
public class OmAppGroup extends Model<OmAppGroup> {
	/**
	 * 主键值
	 */
	@Override
	protected Serializable pkVal() {
		return null;
	}
	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	/** 对应的数据库表名称 */
	public static final String TABLE_NAME = "OM_APP_GROUP" ;
	/* OM_APP_GROUP table's columns definition */
	/** GUID_APP ：应用GUID<br/><br/> */
	public static final String COLUMN_GUID_APP = "guid_app" ;
	/** GUID_GROUP ：工作组GUID<br/><br/> */
	public static final String COLUMN_GUID_GROUP = "guid_group" ;


	/** 字段类型：varchar<br/>字段名：应用GUID<br/>描述： */
	private String guidApp ;

	/** 字段类型：varchar<br/>字段名：工作组GUID<br/>描述： */
	private String guidGroup ;


	/**
	 * Set the 应用GUID.
	 *
	 * @param guidApp
	 *            应用GUID
	 */
	public void setGuidApp(String guidApp) {
		this.guidApp = guidApp == null ? null : guidApp.trim() ;
	}

	/**
	 * Get the 应用GUID.
	 *
	 * @return 应用GUID
	 */
	public String getGuidApp(){
		return this.guidApp ;
	}

	/**
	 * Set the 工作组GUID.
	 *
	 * @param guidGroup
	 *            工作组GUID
	 */
	public void setGuidGroup(String guidGroup) {
		this.guidGroup = guidGroup == null ? null : guidGroup.trim() ;
	}

	/**
	 * Get the 工作组GUID.
	 *
	 * @return 工作组GUID
	 */
	public String getGuidGroup(){
		return this.guidGroup ;
	}

	public String toString(){
		return StringUtil.toString(this) ;
	}
}