package org.tis.tools.abf.module.om.entity;

import com.baomidou.mybatisplus.activerecord.Model;
import com.baomidou.mybatisplus.annotations.TableName;
import org.tis.tools.common.utils.StringUtil;

import java.io.Serializable;

/**
 * Model class of 应用岗位列表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@TableName("OM_APP_POSITION")
public class OmAppPosition extends Model<OmAppPosition> {
	@Override
	protected Serializable pkVal() {
		return null;
	}
	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	/** 对应的数据库表名称 */
	public static final String TABLE_NAME = "OM_APP_POSITION";
	/* OM_APP_POSITION table's columns definition */
	/** GUID_APP ：应用GUID<br/><br/> */
	public static final String COLUMN_GUID_APP = "guid_app" ;
	/** GUID_POSITION ：岗位GUID<br/><br/> */
	public static final String COLUMN_GUID_POSITION = "guid_position" ;
	/** 字段类型：varchar<br/>字段名：应用GUID<br/>描述： */
	private String guidApp ;

	/** 字段类型：varchar<br/>字段名：岗位GUID<br/>描述： */
	private String guidPosition ;


	/**
	 * Set the 应用GUID.
	 *
	 * @param guidApp
	 *            应用GUID
	 */
	public void setGuidApp(String guidApp) {
		this.guidApp = guidApp == null ? null : guidApp.trim() ;
	}

	/**
	 * Get the 应用GUID.
	 *
	 * @return 应用GUID
	 */
	public String getGuidApp(){
		return this.guidApp ;
	}

	/**
	 * Set the 岗位GUID.
	 *
	 * @param guidPosition
	 *            岗位GUID
	 */
	public void setGuidPosition(String guidPosition) {
		this.guidPosition = guidPosition == null ? null : guidPosition.trim() ;
	}

	/**
	 * Get the 岗位GUID.
	 *
	 * @return 岗位GUID
	 */
	public String getGuidPosition(){
		return this.guidPosition ;
	}

	public String toString(){
		return StringUtil.toString(this) ;
	}
}